# Deployment to a production environment is kicked off manually. This actually
# runs two deployment, one is to remove the canary pods if it exists and the
# other deploys to production.
fox:
  production_environment: true
  required_contexts: ["docker", "node"]
  environment: production
  description: "Production"
  payload:
    value_files: ["./config/fox.yml", "./config/_common.yml"]
    release: fox
    namespace: pictures
    track: stable

panda:
  production_environment: true
  required_contexts: ["docker", "node"]
  environment: production
  description: "Production"
  payload:
    value_files: ["./config/panda.yml", "./config/_common.yml"]
    release: panda
    namespace: pictures
    track: stable

cats:
  production_environment: true
  required_contexts: ["docker", "node"]
  environment: production
  description: "Production"
  payload:
    value_files: ["./config/cats.yml", "./config/_common.yml"]
    release: cats
    namespace: pictures
    track: stable

pingu:
  production_environment: true
  required_contexts: ["docker", "node"]
  environment: production
  description: "Production"
  payload:
    value_files: ["./config/pingu.yml", "./config/_common.yml"]
    release: pingu
    namespace: pictures
    track: stable

tiger:
  production_environment: true
  required_contexts: ["docker", "node"]
  environment: production
  description: "Production"
  payload:
    value_files: ["./config/tiger.yml", "./config/_common.yml"]
    release: tiger
    namespace: pictures
    track: stable

# Automatic deployment to a staging environment on every push to master.
beta:
  auto_deploy_on: refs/heads/master
  required_contexts: ["docker", "node"]
  environment: beta
  description: "Beta"
  payload:
    value_files: ["./config/beta.yml", "./config/_common.yml"]
    release: fox-beta
    namespace: pictures
    track: stable
