hostName: maurudor.de

env:
  - name: ORIGIN
    value: maurudor
  - name: ENABLE_TWITTER
    value: "true"
  - name: ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: cats-config
        key: access_key
  - name: ACCESS_KEY_SECRET
    valueFrom:
      secretKeyRef:
        name: cats-config
        key: access_key_secret
  - name: API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cats-config
        key: api_token
  - name: POST_URI
    valueFrom:
      secretKeyRef:
        name: cats-config
        key: post_uri

nodeImagePath: /nfsStorage/cats
