name: cache test

on:
  pull_request:
    branches:
      - main

jobs:
  cacheTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: use Node.js 16
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: check
        run: |
          yarn install --check-cache
