name: "Deploy"
on: ["deployment"]

jobs:
  deployment:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v1"
      - name: "Deploy"
        # Parameters are pulled directly from the GitHub deployment event so the
        # configuration for the job here is very minimal.
        uses: "deliverybot/helm@v1"
        with:
          helm: "helm3"
          token: "${{ github.token }}"
          secrets: "${{ toJSON(secrets) }}"
          version: "${{ github.sha }}"
          chart: "./charts/randompictures"
          values: |
            imageTag: '${{ github.sha }}'
        env:
          KUBECONFIG_FILE: "${{ secrets.KUBECONFIG }}"
