name: docker

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: marudor/randompictures/app:${{ github.sha }}
          username: marudor
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          snapshot: "true"
