name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 19
        uses: actions/setup-node@master
        with:
          node-version: 19
      - name: corepack
        run: corepack enable
      - name: install
        run: pnpm i --frozen-lockfile
      - name: lint
        run: pnpm lint
      - name: types
        run: pnpm tsc
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: marudor/randompictures/app
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          platforms: linux/amd64,linux/arm64
          tags: 'latest,${{ github.sha }}'
  createDeploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - docker
      - node
    steps:
      - name: 'Create Deployment'
        uses: avakar/create-deployment@v1.0.1
        with:
          ref: ${{ github.sha }}
          task: deploy
          environment: beta
          required_contexts: docker,node
          payload: '{"value_files": ["./config/beta.yml","./config/_common.yml"],"release": "fox-beta","namespace": "pictures","track": "stable"}'
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
